<?php
include('templates/frontend/head.php');
include('templates/frontend/header.php');
include('templates/frontend/header-bot.php');
include('templates/frontend/banner-top.php');
include('templates/frontend/content.php');
include('templates/frontend/coupons.php');
include('templates/frontend/footer.php');
?>